languageCode = "ja"
languageName = "Japanese"
languageDirection = "ltr"
weight = 1

title = "jenro.fun"

copyright = "Copyright 2025 Jenro Jupitel. All rights reserved."

[params]
  dateFormat = "January 2, 2006"

  mainSections = ["section1", "section2"]
  description = "Jenro's space on the internet"

[params.author]
  name = "Jenro Jupitel"
  image = "img/author.jpg"
  headline = "Find something cool with Jenro."
  bio = "I’m a casual gamer who’s also a stepartist. This site is a springboard for my ideals and the things that I experience to be fun, from my primary interests, to my hobbies, and my skills."
  links = [
     { email = "mailto:jenrothetactician@gmail.com" },
     { discord = "https://discord.com/users/jenro7" },
     { snapchat = "https://snapchat.com/add/mindthetimes" },
     { steam = "https://steamcommunity.com/id/jenrothetactician" },
     { x-twitter = "https://twitter.com/mindthetimes" },
     { youtube = "https://www.youtube.com/@jenro7" },
   ]
